import type {
  Project,
  Queue,
  Job,
  Worker,
  ExecutionLog,
  DeadLetterJob,
  DashboardMetrics,
  MetricPoint,
} from '@/types';

const generateTimestamp = (minutesAgo: number): string => {
  const date = new Date(Date.now() - minutesAgo * 60000);
  return date.toISOString();
};

const generateMetricPoints = (count: number, baseValue: number, variance: number): MetricPoint[] => {
  return Array.from({ length: count }, (_, i) => ({
    timestamp: generateTimestamp((count - i) * 5),
    value: Math.max(0, baseValue + Math.random() * variance - variance / 2),
  }));
};

export const mockProjects: Project[] = [
  {
    id: 'proj-1',
    name: 'E-Commerce Platform',
    description: 'Main e-commerce backend services',
    status: 'active',
    queueCount: 5,
    jobCount: 1247,
    workerCount: 12,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-03-10T14:30:00Z',
  },
  {
    id: 'proj-2',
    name: 'Payment Processing',
    description: 'Payment gateway and transaction handling',
    status: 'active',
    queueCount: 3,
    jobCount: 856,
    workerCount: 8,
    createdAt: '2024-01-20T09:00:00Z',
    updatedAt: '2024-03-12T11:15:00Z',
  },
  {
    id: 'proj-3',
    name: 'Data Analytics',
    description: 'Data pipeline and analytics jobs',
    status: 'active',
    queueCount: 4,
    jobCount: 2341,
    workerCount: 15,
    createdAt: '2024-02-01T08:00:00Z',
    updatedAt: '2024-03-11T16:45:00Z',
  },
  {
    id: 'proj-4',
    name: 'Email Service',
    description: 'Email notification and marketing',
    status: 'inactive',
    queueCount: 2,
    jobCount: 432,
    workerCount: 4,
    createdAt: '2024-02-10T11:00:00Z',
    updatedAt: '2024-03-05T09:20:00Z',
  },
  {
    id: 'proj-5',
    name: 'Legacy Integration',
    description: 'Legacy system migration tasks',
    status: 'archived',
    queueCount: 1,
    jobCount: 89,
    workerCount: 2,
    createdAt: '2023-11-15T14:00:00Z',
    updatedAt: '2024-02-28T10:00:00Z',
  },
];

export const mockQueues: Queue[] = [
  {
    id: 'queue-1',
    name: 'primary-queue',
    projectId: 'proj-1',
    projectName: 'E-Commerce Platform',
    status: 'active',
    priority: 10,
    jobsPending: 45,
    jobsProcessing: 12,
    jobsCompleted: 892,
    jobsFailed: 23,
    throughput: 156,
    avgLatency: 234,
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'queue-2',
    name: 'payment-critical',
    projectId: 'proj-2',
    projectName: 'Payment Processing',
    status: 'active',
    priority: 20,
    jobsPending: 12,
    jobsProcessing: 8,
    jobsCompleted: 1567,
    jobsFailed: 3,
    throughput: 89,
    avgLatency: 45,
    createdAt: '2024-01-20T09:00:00Z',
  },
  {
    id: 'queue-3',
    name: 'data-pipeline',
    projectId: 'proj-3',
    projectName: 'Data Analytics',
    status: 'active',
    priority: 5,
    jobsPending: 234,
    jobsProcessing: 45,
    jobsCompleted: 4521,
    jobsFailed: 89,
    throughput: 312,
    avgLatency: 567,
    createdAt: '2024-02-01T08:00:00Z',
  },
  {
    id: 'queue-4',
    name: 'email-bulk',
    projectId: 'proj-4',
    projectName: 'Email Service',
    status: 'paused',
    priority: 3,
    jobsPending: 123,
    jobsProcessing: 0,
    jobsCompleted: 2341,
    jobsFailed: 156,
    throughput: 0,
    avgLatency: 1200,
    createdAt: '2024-02-10T11:00:00Z',
  },
  {
    id: 'queue-5',
    name: 'retry-queue',
    projectId: 'proj-1',
    projectName: 'E-Commerce Platform',
    status: 'active',
    priority: 2,
    jobsPending: 67,
    jobsProcessing: 5,
    jobsCompleted: 234,
    jobsFailed: 12,
    throughput: 34,
    avgLatency: 4500,
    createdAt: '2024-01-15T10:05:00Z',
  },
];

export const mockJobs: Job[] = [
  {
    id: 'job-1',
    name: 'Process Order #12345',
    queueId: 'queue-1',
    queueName: 'primary-queue',
    projectId: 'proj-1',
    projectName: 'E-Commerce Platform',
    status: 'running',
    priority: 10,
    attempts: 1,
    maxAttempts: 3,
    payload: { orderId: '12345', userId: 'user-123' },
    workerId: 'worker-1',
    workerName: 'node-1',
    startedAt: generateTimestamp(5),
    createdAt: generateTimestamp(10),
    updatedAt: generateTimestamp(5),
  },
  {
    id: 'job-2',
    name: 'Send Welcome Email',
    queueId: 'queue-1',
    queueName: 'primary-queue',
    projectId: 'proj-1',
    projectName: 'E-Commerce Platform',
    status: 'completed',
    priority: 5,
    attempts: 1,
    maxAttempts: 3,
    payload: { email: 'newuser@example.com', template: 'welcome' },
    result: { messageId: 'msg-abc123', sent: true },
    workerId: 'worker-2',
    workerName: 'node-2',
    startedAt: generateTimestamp(25),
    completedAt: generateTimestamp(24),
    duration: 1250,
    createdAt: generateTimestamp(30),
    updatedAt: generateTimestamp(24),
  },
  {
    id: 'job-3',
    name: 'Payment Gateway Call',
    queueId: 'queue-2',
    queueName: 'payment-critical',
    projectId: 'proj-2',
    projectName: 'Payment Processing',
    status: 'pending',
    priority: 20,
    attempts: 0,
    maxAttempts: 5,
    payload: { amount: 99.99, currency: 'USD', customerId: 'cust-456' },
    createdAt: generateTimestamp(2),
    updatedAt: generateTimestamp(2),
  },
  {
    id: 'job-4',
    name: 'Generate Daily Report',
    queueId: 'queue-3',
    queueName: 'data-pipeline',
    projectId: 'proj-3',
    projectName: 'Data Analytics',
    status: 'failed',
    priority: 3,
    attempts: 3,
    maxAttempts: 3,
    payload: { reportType: 'daily', date: '2024-03-10' },
    error: 'Database connection timeout after 30s',
    workerId: 'worker-5',
    workerName: 'node-5',
    startedAt: generateTimestamp(60),
    completedAt: generateTimestamp(58),
    duration: 30000,
    createdAt: generateTimestamp(65),
    updatedAt: generateTimestamp(58),
  },
  {
    id: 'job-5',
    name: 'Sync Inventory',
    queueId: 'queue-1',
    queueName: 'primary-queue',
    projectId: 'proj-1',
    projectName: 'E-Commerce Platform',
    status: 'retrying',
    priority: 8,
    attempts: 2,
    maxAttempts: 5,
    payload: { warehouse: 'wh-east' },
    error: 'Connection refused',
    workerId: 'worker-3',
    workerName: 'node-3',
    startedAt: generateTimestamp(15),
    createdAt: generateTimestamp(20),
    updatedAt: generateTimestamp(12),
  },
  {
    id: 'job-6',
    name: 'Bulk Email Campaign',
    queueId: 'queue-4',
    queueName: 'email-bulk',
    projectId: 'proj-4',
    projectName: 'Email Service',
    status: 'queued',
    priority: 2,
    attempts: 0,
    maxAttempts: 3,
    payload: { campaignId: 'camp-789', recipients: 12500 },
    scheduledAt: generateTimestamp(-30),
    createdAt: generateTimestamp(45),
    updatedAt: generateTimestamp(45),
  },
  {
    id: 'job-7',
    name: 'Data Aggregation',
    queueId: 'queue-3',
    queueName: 'data-pipeline',
    projectId: 'proj-3',
    projectName: 'Data Analytics',
    status: 'running',
    priority: 5,
    attempts: 1,
    maxAttempts: 2,
    payload: { dataset: 'users-2024', aggregation: 'monthly' },
    workerId: 'worker-4',
    workerName: 'node-4',
    startedAt: generateTimestamp(8),
    createdAt: generateTimestamp(12),
    updatedAt: generateTimestamp(8),
  },
  {
    id: 'job-8',
    name: 'Refund Transaction #tx-999',
    queueId: 'queue-2',
    queueName: 'payment-critical',
    projectId: 'proj-2',
    projectName: 'Payment Processing',
    status: 'completed',
    priority: 20,
    attempts: 1,
    maxAttempts: 5,
    payload: { transactionId: 'tx-999', amount: 49.99 },
    result: { refundId: 'ref-111', status: 'processed' },
    workerId: 'worker-1',
    workerName: 'node-1',
    startedAt: generateTimestamp(40),
    completedAt: generateTimestamp(39),
    duration: 890,
    createdAt: generateTimestamp(42),
    updatedAt: generateTimestamp(39),
  },
];

export const mockWorkers: Worker[] = [
  {
    id: 'worker-1',
    name: 'node-1',
    status: 'online',
    queues: ['queue-1', 'queue-2'],
    queuesNames: ['primary-queue', 'payment-critical'],
    jobsCompleted: 1567,
    jobsFailed: 23,
    lastHeartbeat: generateTimestamp(0),
    uptime: 3456789,
    cpuUsage: 45,
    memoryUsage: 62,
    version: '1.2.3',
    metadata: { region: 'us-east-1', instance: 'm5.large' },
  },
  {
    id: 'worker-2',
    name: 'node-2',
    status: 'busy',
    queues: ['queue-1', 'queue-3'],
    queuesNames: ['primary-queue', 'data-pipeline'],
    currentJob: mockJobs[0],
    jobsCompleted: 1234,
    jobsFailed: 12,
    lastHeartbeat: generateTimestamp(0.5),
    uptime: 2134567,
    cpuUsage: 89,
    memoryUsage: 75,
    version: '1.2.3',
    metadata: { region: 'us-east-1', instance: 'm5.large' },
  },
  {
    id: 'worker-3',
    name: 'node-3',
    status: 'online',
    queues: ['queue-1', 'queue-5'],
    queuesNames: ['primary-queue', 'retry-queue'],
    jobsCompleted: 892,
    jobsFailed: 45,
    lastHeartbeat: generateTimestamp(1),
    uptime: 1234567,
    cpuUsage: 32,
    memoryUsage: 48,
    version: '1.2.2',
    metadata: { region: 'us-west-2', instance: 'm5.large' },
  },
  {
    id: 'worker-4',
    name: 'node-4',
    status: 'error',
    queues: ['queue-3'],
    queuesNames: ['data-pipeline'],
    jobsCompleted: 456,
    jobsFailed: 89,
    lastHeartbeat: generateTimestamp(120),
    uptime: 2345678,
    cpuUsage: 0,
    memoryUsage: 0,
    version: '1.2.3',
    metadata: { region: 'us-west-2', instance: 'm5.large' },
  },
  {
    id: 'worker-5',
    name: 'node-5',
    status: 'offline',
    queues: ['queue-2', 'queue-4'],
    queuesNames: ['payment-critical', 'email-bulk'],
    jobsCompleted: 789,
    jobsFailed: 34,
    lastHeartbeat: generateTimestamp(300),
    uptime: 0,
    cpuUsage: 0,
    memoryUsage: 0,
    version: '1.2.1',
    metadata: { region: 'eu-west-1', instance: 'm5.medium' },
  },
];

export const mockExecutionLogs: ExecutionLog[] = [
  {
    id: 'log-1',
    jobId: 'job-1',
    jobName: 'Process Order #12345',
    queueId: 'queue-1',
    queueName: 'primary-queue',
    workerId: 'worker-1',
    workerName: 'node-1',
    level: 'info',
    message: 'Order processing started',
    timestamp: generateTimestamp(5),
    duration: 50,
  },
  {
    id: 'log-2',
    jobId: 'job-1',
    jobName: 'Process Order #12345',
    queueId: 'queue-1',
    queueName: 'primary-queue',
    workerId: 'worker-1',
    workerName: 'node-1',
    level: 'debug',
    message: 'Fetching order details from database',
    timestamp: generateTimestamp(4.9),
    duration: 120,
  },
  {
    id: 'log-3',
    jobId: 'job-2',
    jobName: 'Send Welcome Email',
    queueId: 'queue-1',
    queueName: 'primary-queue',
    workerId: 'worker-2',
    workerName: 'node-2',
    level: 'info',
    message: 'Email sent successfully',
    timestamp: generateTimestamp(24),
    duration: 1250,
  },
  {
    id: 'log-4',
    jobId: 'job-4',
    jobName: 'Generate Daily Report',
    queueId: 'queue-3',
    queueName: 'data-pipeline',
    workerId: 'worker-5',
    workerName: 'node-5',
    level: 'error',
    message: 'Database connection timeout after 30s',
    timestamp: generateTimestamp(58),
    duration: 30000,
    metadata: { retryAttempt: 3, maxRetries: 3 },
  },
  {
    id: 'log-5',
    jobId: 'job-5',
    jobName: 'Sync Inventory',
    queueId: 'queue-1',
    queueName: 'primary-queue',
    workerId: 'worker-3',
    workerName: 'node-3',
    level: 'warn',
    message: 'Connection refused, retrying in 5s',
    timestamp: generateTimestamp(15),
    metadata: { retryAttempt: 2, delay: 5000 },
  },
  {
    id: 'log-6',
    jobId: 'job-8',
    jobName: 'Refund Transaction #tx-999',
    queueId: 'queue-2',
    queueName: 'payment-critical',
    workerId: 'worker-1',
    workerName: 'node-1',
    level: 'info',
    message: 'Refund processed successfully',
    timestamp: generateTimestamp(39),
    duration: 890,
    metadata: { refundId: 'ref-111', amount: 49.99 },
  },
];

export const mockDeadLetterJobs: DeadLetterJob[] = [
  {
    id: 'dlq-1',
    originalJobId: 'job-4',
    jobName: 'Generate Daily Report',
    queueId: 'queue-3',
    queueName: 'data-pipeline',
    projectId: 'proj-3',
    projectName: 'Data Analytics',
    error: 'Database connection timeout after 30s',
    attempts: 3,
    failedAt: generateTimestamp(58),
    payload: { reportType: 'daily', date: '2024-03-10' },
    canRetry: true,
  },
  {
    id: 'dlq-2',
    originalJobId: 'job-xyz',
    jobName: 'External API Call',
    queueId: 'queue-1',
    queueName: 'primary-queue',
    projectId: 'proj-1',
    projectName: 'E-Commerce Platform',
    error: 'HTTP 503: Service Unavailable',
    attempts: 5,
    failedAt: generateTimestamp(120),
    payload: { endpoint: '/api/v2/sync', method: 'POST' },
    canRetry: true,
  },
  {
    id: 'dlq-3',
    originalJobId: 'job-abc',
    jobName: 'Batch Import Users',
    queueId: 'queue-4',
    queueName: 'email-bulk',
    projectId: 'proj-4',
    projectName: 'Email Service',
    error: 'Invalid CSV format: missing required column "email"',
    attempts: 1,
    failedAt: generateTimestamp(240),
    payload: { fileKey: 'imports/users-2024-03-10.csv' },
    canRetry: true,
  },
];

export const mockDashboardMetrics: DashboardMetrics = {
  totalJobs: 15489,
  jobsCompleted: 12456,
  jobsFailed: 234,
  jobsPending: 523,
  jobsRunning: 76,
  totalWorkers: 8,
  workersOnline: 6,
  totalQueues: 5,
  queuesActive: 4,
  throughput: 456,
  avgLatency: 234,
  successRate: 98.2,
};

export const mockThroughputData = generateMetricPoints(24, 450, 100);

export const mockLatencyData = generateMetricPoints(24, 200, 50);

export const mockQueueDepthData = generateMetricPoints(24, 100, 30);

export const mockJobsByStatus = [
  { status: 'completed', count: 12456 },
  { status: 'running', count: 76 },
  { status: 'pending', count: 523 },
  { status: 'failed', count: 234 },
  { status: 'retrying', count: 45 },
];

export const mockJobsByQueue = [
  { name: 'primary-queue', value: 1247 },
  { name: 'payment-critical', value: 856 },
  { name: 'data-pipeline', value: 2341 },
  { name: 'email-bulk', value: 432 },
  { name: 'retry-queue', value: 89 },
];

export const mockWorkerHealth = [
  { name: 'node-1', value: 98 },
  { name: 'node-2', value: 95 },
  { name: 'node-3', value: 99 },
  { name: 'node-4', value: 0 },
  { name: 'node-5', value: 0 },
];

export const mockHourlyJobs = [
  { hour: '00:00', completed: 234, failed: 2 },
  { hour: '01:00', completed: 189, failed: 1 },
  { hour: '02:00', completed: 156, failed: 5 },
  { hour: '03:00', completed: 112, failed: 0 },
  { hour: '04:00', completed: 98, failed: 2 },
  { hour: '05:00', completed: 145, failed: 1 },
  { hour: '06:00', completed: 267, failed: 3 },
  { hour: '07:00', completed: 412, failed: 2 },
  { hour: '08:00', completed: 523, failed: 8 },
  { hour: '09:00', completed: 612, failed: 12 },
  { hour: '10:00', completed: 589, failed: 7 },
  { hour: '11:00', completed: 634, failed: 9 },
];
